### ISSUE TITLE
[BUG] If you set a snapshot '-s' parameter, no one can join that master node

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#35] opened 2015-04-13 00:39 UTC
Hey @otoolep ,

I just spent a few minutes trying to figure out why I couldn't join a master node. It would stall on:
```
2015/04/12 20:27:58 [ERROR] Error loading snapshot: open data/snapshot: no such file or directory
2015/04/12 20:27:58 [INFO ] Attempting to join leader at xxx.xx.xx.xx:4002
```

I finally figured out that if I remove the -s snapshot parameter on the master startup script, it works fine:

This won't accept joiners:
`$GOPATH/bin/rqlite -s 50 -p 4002 data`

This will:
`$GOPATH/bin/rqlite -p 4002 data`

**Comment by otoolep** [comment] 2015-04-13 05:01
Do any writes take place on the leader, before the attempted join, such that the leader snapshots and then blocks?

**Comment by otoolep** [comment] 2015-04-13 05:02
Do you still see this issue if the snapshot value is very large e.g. 1,000,000,000 -- I am trying to see if a snapshot actually needs to take place for this to happen.

**Comment by tchoulihan** [comment] 2015-04-13 12:30
> Do any writes take place on the leader, before the attempted join, such that the leader snapshots and then blocks?

Yes, I did some writes(<100) before I had the 2nd node join.

> Do you still see this issue if the snapshot value is very large e.g. 1,000,000,000 -- I am trying to see if a snapshot actually needs to take place for this to happen.

I just tested this with a -s 1000000 , and it joined correctly.

So maybe the bug is actually after a snapshot occurs, no joins are working?

**Comment by otoolep** [comment] 2015-04-14 00:52
Yeah, that sounds likely. I'll try to take a look soon.

**Comment by otoolep** [comment] 2015-04-15 07:13
I can't reproduce this.

Shell 1:
```
$ ./rqlite -s 2 ~/node.1
2015/04/15 00:09:51 [INFO ] Raft random seed initialized
2015/04/15 00:09:51 [INFO ] Raft commands registered
2015/04/15 00:09:51 [INFO ] Initializing Raft Server: /home/philip/node.1
2015/04/15 00:09:51 [INFO ] Loading latest snapshot, if any, from disk
2015/04/15 00:09:51 [INFO ] no snapshot found
2015/04/15 00:09:51 [INFO ] Initializing new cluster
2015/04/15 00:09:51 [INFO ] Initializing HTTP server
```

Shell 2:
```
$ curl -L -XPOST localhost:4001/db?pretty -d 'CREATE TABLE foo1 (id integer not null primary key, name text)'                                                                                                    
{
    "failures": []
}
$ curl -L -XPOST localhost:4001/db?pretty -d 'CREATE TABLE foo2 (id integer not null primary key, name text)'                                                                                                    
{
    "failures": []
}
```

Back to shell 1, snapshot has taken place:
```
2015/04/15 00:09:57 [INFO ] Committed log entries snapshot threshold reached, starting snapshot
2015/04/15 00:09:57 [INFO ] http://localhost:4001: snapshot of 3 events at index 3 completed
```

Then a successful join at shell 3:
```
$ ./rqlite -join localhost:4001 -p 4002 ~/node.2
2015/04/15 00:10:03 [INFO ] Raft random seed initialized
2015/04/15 00:10:03 [INFO ] Raft commands registered
2015/04/15 00:10:03 [INFO ] Initializing Raft Server: /home/philip/node.2
2015/04/15 00:10:03 [INFO ] Loading latest snapshot, if any, from disk
2015/04/15 00:10:03 [INFO ] no snapshot found
2015/04/15 00:10:03 [INFO ] Attempting to join leader at localhost:4001
2015/04/15 00:10:03 [INFO ] Initializing HTTP server
2015/04/15 00:10:03 [INFO ] Listening at http://localhost:4002
```

**Comment by otoolep** [comment] 2015-04-15 07:13
@tchoulihan -- can you please post a session like above, showing the failure?

**Comment by otoolep** [comment] 2015-04-15 07:14
I'm going to close this, since it looks fine. Can you check your networking? And feel free to re-open (or create a new ticket) if you can produce a detailed trace.

**Closed by otoolep** 2015-04-15 07:14 UTC

**Comment by tchoulihan** [comment] 2015-04-15 13:04
Yep, leave this closed, I just tried to replicate this issue with hundreds of writes and couldn't get the same error I used to. I've noticed the snapshot directories are empty though even when using -s 2 or -s 50. Is this correct?

**Comment by otoolep** [comment] 2015-04-15 14:17
They are not empty for me.

**Comment by tchoulihan** [comment] 2015-04-15 14:19
@otoolep i updated my comment, the original email sent you a bad one, sorry about that.
